name: Push events on master branch

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Print python version
        run: python -V
      - name: Install dependencies
        run: make install-dev
      - name: Test with pytest
        run: make test
